version: 2
updates:
  # npm dependencies for core
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "kaseken"

  # npm dependencies for in-app-messaging
  - package-ecosystem: "npm"
    directory: "/packages/in-app-messaging"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "kaseken"

  # npm dependencies for notification
  - package-ecosystem: "npm"
    directory: "/packages/notification"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "kaseken"

  # npm dependencies for utilities
  - package-ecosystem: "npm"
    directory: "/packages/utilities"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "kaseken"

  # npm dependencies for variables
  - package-ecosystem: "npm"
    directory: "/packages/variables"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "kaseken"

  # npm dependencies for visual-tracking
  - package-ecosystem: "npm"
    directory: "/packages/visual-tracking"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "kaseken"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    assignees:
      - "kaseken"