version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:16.17
    working_directory: ~/project
    environment:
      YARN_CACHE_FOLDER: '~/.cache/yarn'

commands:
  attach_project:
    steps:
      - attach_workspace:
          at: ~/project

jobs:
  install-dependencies:
    executor: default
    steps:
      - checkout
      - attach_project
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install project dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: .

  lint-and-typecheck:
    executor: default
    steps:
      - attach_project
      - run:
          name: Lint files
          command: yarn lint
      - run:
          name: Typecheck files
          command: yarn typecheck

  build-package:
    executor: default
    steps:
      - attach_project
      - run:
          name: Build packages in monorepo
          command: yarn lerna run prepare
      - run:
          name: Verify paths for types
          command: node scripts/check-types-path.js

  test:
    executor: default
    steps:
      - attach_project
      - run:
          name: Test packages in monorepo
          command: yarn test

workflows:
  build-and-test:
    jobs:
      - install-dependencies
      - lint-and-typecheck:
          requires:
            - install-dependencies
      - build-package:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
