name: Publish packages to npmjs.com
on:
  workflow_dispatch:
env:
  NODE_VERSION: 24
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 'npmjs.com'
    timeout-minutes: 40
    # Publish on public repository.
    if: github.repository == 'plaidev/karte-react-native'
    permissions:
      id-token: write # Required for OIDC
      contents: write # Required for tagging.
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - name: Show npm version
        run: npm --version
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build packages
        run: yarn lerna run prepare
      - name: Run linting
        run: yarn lint
      - name: Run type checking
        run: yarn typecheck
      - name: Run tests
        run: yarn test
      - name: Configure Git
        run: |
          git config --global user.email "git@users.noreply.github.com"
          git config --global user.name "github actions"
      # Publishes packages with unpublished versions.
      - name: Publish packages
        run: yarn lerna publish from-package --yes
      # Creates unexisting version tags (= published version tags).
      - name: Create version tags
        run: |
          git fetch --tags
          yarn lerna exec \$LERNA_ROOT_PATH/scripts/ci-create-tag.sh
          git push --tags
      - name: Notify Slack on success
        if: success()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            ✅ Successfully published packages to npmjs.com
          SLACK_COLOR: success
      - name: Notify Slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            ❌ Failed to publish packages to npmjs.com
          SLACK_COLOR: failure
