name: "Require version bump for package changes"
on:
  pull_request:
    branches: [master, develop]
    paths:
      - "packages/**"
env:
  NODE_VERSION: 24
jobs:
  check:
    if: github.repository != 'plaidev/karte-react-native'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0 # Fetches Git tags.
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - name: Show npm version
        run: npm --version
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check version bumps
        id: version_check
        run: yarn lerna exec --since origin/master --no-bail --exclude-dependents \$LERNA_ROOT_PATH/scripts/ci-check-version-bump.sh
