name: Test Build Old App Android
on:
  # TODO: Enable to run automatically before release.
  workflow_dispatch:
env:
  NODE_VERSION: 20
  JAVA_VERSION: 17
jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Install yalc globally
        run: npm install -g yalc
      - name: Install root dependencies
        run: yarn install --frozen-lockfile
      - name: Build packages
        run: npx lerna run build
      - name: Publish packages to yalc
        run: npx lerna exec -- yalc publish
      - name: Add local KARTE packages via yalc
        working-directory: build_tests/OldAppTest
        run: yalc add @react-native-karte/utilities @react-native-karte/core @react-native-karte/in-app-messaging @react-native-karte/notification @react-native-karte/variables @react-native-karte/visual-tracking
      - name: Install OldAppTest dependencies
        working-directory: build_tests/OldAppTest
        run: npm install
      - name: Build Android app
        working-directory: build_tests/OldAppTest/android
        run: ./gradlew assembleRelease
